# Generated by Django 4.1.4 on 2022-12-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donarsinfo',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
