# Generated by Django 4.1.4 on 2022-12-23 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_donarsinfo_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donarsinfo',
            name='price',
        ),
    ]
